### PR TITLE
Converted handlebar templates

### PR DESCRIPTION
**Pull request by AnPucel**
## Description
```
mustache_to_handlebars -out_dir=handlebar \
     -handlebars_if_tags="isArray isReadOnly isXmlAttribute isNullable isMap notes isEnum isDeprecated deprecated isQueryParam isPathParam isAdditionalPropertiesTrue isContainer isBasicBasic isKeyInHeader supportsRetry isDeepObject isOAuth isString hasValidation isBasicBearer isApiKey isBoolean hasRequired hasHttpSignatureMethods useRestSharp hasImport isFile isDate supportsAsync isBasic useHttpClient hasOnlyReadOnly isKeyInCookie isKeyInQuery isHttpSignature hasAuthMethods isDateTime isPrimitiveType useGenericHost optionalMethodArgument validatable useCompareNetObjects consumes useOneOfDiscriminatorLookup" \
     -handlebars_each_tags="allParams apis models vendorExtensions.x-implements bodyParams pathParams imports operation enumVars allowableValues queryParams vars children formParams headerParams responses authMethods mappedModels parentVars readWriteVars caseInsensitiveResponseHeaders headers produces items.vars" \
     -handlebars_with_tags="parent discriminator withXml description required model anyOf appName version apiInfo operations returnTypeIsPrimitive items infoEmail oneOf defaultValue returnType vendorExtensions.x-is-one-of-interface vendorExtensions.x-go-custom-tag appDescription vendorExtensions.x-is-value-type lambda.titlecase vendorExtensions.x-discriminator-value vendorExtensions.x-modifiers lambda.camelcase_param vendorExtensions.x-emit-default-value lambda.lowercase vendorExtensions.x-csharp-value-type vendorExtensions.x-enum-byte summary multiTarget minLength bodyParam items.isEnum maximum aneOf servers.[0] pattern netStandard licenseUrl minimum nonPublicApi conditionalSerialization maxLength termsOfService responses.[0]" \
        templates
```

## How has this been tested?

> Please describe the tests you ran.

### CODE REVIEW

**Review by dhuckins — APPROVED** [review]

**Comment by AnPucel** [comment]
Prematurely marked this ready for review. Fixing the model templates/build

**Comment by averche** [comment]
The headers in the model documentation pages seem to be misformatted. There is also a lot of extra spacing introduced (particularly in the model .cs files). Can those be addressed with `dotnet format`?

**Comment by AnPucel** [comment]
> The headers in the model documentation pages seem to be misformatted. There is also a lot of extra spacing introduced (particularly in the model .cs files). Can those be addressed with `dotnet format`?

Unfortunately `dotnet format` doesn't do this by default. it requires an .editorconfig, which seems to be more local. I want the spacing to be removed from the templates as best as I can. I forgot I need to fix those headers though... Most of the files should be formatted properly. 

The model files, I'm fixing now.

**Comment by dhuckins** [comment]
for whitespace, have we tried https://handlebarsjs.com/guide/expressions.html#whitespace-control ?
(note: this is the JS package, likely different than what's in openapi-generator but can try)

**Comment by AnPucel** [comment]
> for whitespace, have we tried https://handlebarsjs.com/guide/expressions.html#whitespace-control ? (note: this is the JS package, likely different than what's in openapi-generator but can try)

Yep! This is implemented in some of them. It's just tedious b/c the templates don't actually behave like they do in this [playground](http://tryhandlebarsjs.com/), so it's a lot of trial and error to get it spaced properly

**Comment by AnPucel** [comment]
I've removed as much whitespace that seems reasonable. I can address it in later PRs as well

**Comment by AnPucel** [comment]
I've removed as much whitespace that seems reasonable. I can address it in later PRs as well

**Pull request merged**
